#######################################################################################
# Book settings
title : Scientific Python QuickStart
author: Leila Inigo 
logo: 'qe-logo-large.png'

# Information about where the book exists on the web
description: >-
  A brief introduction to Python programming for scientific applications.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/leilaicruz/jupyter-book
  path_to_book                : mini_book/docs/_build/html
  branch                      : master 

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"

launch_buttons:
  thebelab                  : true